# Generated by Django 4.0.4 on 2022-05-03 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_mainuser_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='mainuser',
            options={'permissions': (('can_go_in_non_ac_bus', 'To provide non-AC Bus facility'), ('can_go_in_ac_bus', 'To provide AC-Bus facility'), ('can_stay_ac-room', 'To provide staying at AC room'), ('can_not_stay_ac-room', 'To provide staying at Non-AC room'), ('can_go_dehradoon', 'Trip to Dehradoon'), ('can_go_mussoorie', 'Trip to Mussoorie'), ('can_go_haridwaar', 'Trip to Haridwaar'), ('can_go_rishikesh', 'Trip to Rishikesh'))},
        ),
        migrations.RenameField(
            model_name='mainuser',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='mainuser',
            old_name='date_modified',
            new_name='modified_at',
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.userrole')),
            ],
        ),
        migrations.AddField(
            model_name='mainuser',
            name='user_roles',
            field=models.ManyToManyField(to='Users.userrole'),
        ),
    ]
