# Generated by Django 4.0.4 on 2022-05-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_userrole_alter_mainuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='user_roles',
            field=models.ManyToManyField(null=True, to='Users.userrole'),
        ),
    ]
