# Generated by Django 4.0.4 on 2022-05-06 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_mainuser_user_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='permissions',
            name='role',
        ),
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.permissions')),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.userrole')),
            ],
        ),
    ]
