# Generated by Django 4.0.4 on 2022-05-10 06:25

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_mainuser_options_remove_permissions_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(default='Tanzania', max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='age',
        ),
        migrations.AddField(
            model_name='userrole',
            name='permissions',
            field=models.ManyToManyField(to='Users.permissions'),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='user_roles',
            field=models.ManyToManyField(to='Users.userrole'),
        ),
        migrations.DeleteModel(
            name='RolePermissions',
        ),
        migrations.AddField(
            model_name='mainuser',
            name='contacts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.contacts'),
        ),
    ]
