# Generated by Django 4.0.4 on 2022-05-10 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_userrole_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='permissions',
            new_name='permission',
        ),
    ]
