# Generated by Django 4.0.4 on 2022-05-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_mainuser_is_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='nationality',
            field=models.CharField(default='United Republic of Tanzania', max_length=100, null=True),
        ),
    ]
