# Generated by Django 4.0.4 on 2022-05-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_mainuser_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='village',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='ward',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(default='United Republic Of Tanzania', max_length=100, null=True),
        ),
    ]
