# Generated by Django 4.0.4 on 2022-05-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0002_rename_user_id_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(upload_to='students/<django.db.models.fields.related.OneToOneField>/profile_image'),
        ),
    ]
