# Generated by Django 4.0.4 on 2022-05-10 13:56

import SMS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0005_alter_student_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(upload_to=SMS.models.Student.userDirectoryPath),
        ),
    ]
