# Generated by Django 4.0.4 on 2022-05-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0011_alter_student_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(to='SMS.subjects'),
        ),
    ]
