# Generated by Django 4.0.4 on 2022-05-25 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0013_alter_course_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=200)),
                ('assingment_file', models.FileField(upload_to='')),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SMS.instructor')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SMS.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='StudentsAssignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_done', models.FileField(null=True, upload_to='')),
                ('is_completed', models.BooleanField(default=False)),
                ('submitted_on', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('assingment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SMS.assignments')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SMS.student')),
            ],
        ),
    ]
