# Generated by Django 4.0.4 on 2022-05-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0014_assignments_studentsassignments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsassignments',
            old_name='assingment',
            new_name='assignment',
        ),
    ]
