# Generated by Django 4.0.4 on 2022-05-30 15:23

import SMS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0016_courseitemtype_assignments_created_by_courseoutline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=SMS.models.Instructor.userDirectoryPath),
        ),
        migrations.AddField(
            model_name='instructor',
            name='teacher_UUID',
            field=models.CharField(blank=True, default=SMS.models.Instructor.random_UUID_Generator, editable=False, max_length=100),
        ),
    ]
