# Generated by Django 4.0.4 on 2022-05-30 15:31

import SMS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0017_instructor_profile_image_instructor_teacher_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='teacher_UUID',
            field=models.CharField(blank=True, default=SMS.models.Instructor.random_UUID_Generator, editable=False, max_length=100, null=True),
        ),
    ]
