# Generated by Django 4.0.4 on 2022-05-30 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_location_district_location_village_location_ward_and_more'),
        ('SMS', '0018_alter_instructor_teacher_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.location'),
        ),
    ]
