# Generated by Django 4.0.4 on 2022-05-30 15:56

import SMS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0020_specializations_instructor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=SMS.models.Instructor.userDirectoryPath),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=SMS.models.Student.userDirectoryPath),
        ),
    ]
