# Generated by Django 4.0.4 on 2022-06-01 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0021_alter_instructor_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseitems',
            name='course_outline',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='SMS.courseoutline'),
        ),
    ]
