# Generated by Django 4.0.4 on 2022-06-01 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0022_alter_courseitems_course_outline'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseitems',
            name='course_item_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='SMS.courseitemtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseitems',
            name='course_outline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SMS.courseoutline'),
        ),
    ]
