# Generated by Django 4.0.4 on 2022-06-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0023_courseitems_course_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseitems',
            name='percentage',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
